language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.3
      dist: trusty

cache:
  directories:
    - $HOME/.composer

before_install:
  - sudo sed 's/mozilla.DST_Root_CA_X3.crt/!mozilla\/DST_Root_CA_X3.crt/' -i /etc/ca-certificates.conf
  - sudo update-ca-certificates 
  - composer self-update
  - composer clear-cache

install:
  composer update --no-interaction --no-ansi --optimize-autoloader --prefer-dist

before_script:
  - export XDEBUG_MODE=coverage

script:
  - php -derror_reporting=32759 vendor/bin/phpunit --configuration phpunit.xml.dist --no-coverage

# after_success:
#   - travis_retry php vendor/bin/php-coveralls
